# Generated by Django 4.2.1 on 2023-06-09 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idcomuna', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('idespecialidad', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('idmedico', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('run', models.CharField(max_length=45)),
                ('especialidad', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idPaciente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('run', models.CharField(max_length=45)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente_ProfesionalSalud',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('idusuariopaciente', models.CharField(max_length=45)),
                ('idusuarioprofsinalsalud', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idregion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='TipoInstrumento',
            fields=[
                ('idTipoInstrumento', models.IntegerField(primary_key=True, serialize=False)),
                ('Tipo', models.CharField(max_length=60)),
                ('Descripcion', models.CharField(max_length=300)),
                ('PreguntasInstrumento_id', models.IntegerField()),
                ('PreguntasInstrumento_TipoRespuesta_idTipoRespuesta', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45)),
                ('contraseña', models.CharField(max_length=45)),
                ('nombrecompleto', models.CharField(max_length=45)),
                ('usuariocol', models.CharField(max_length=45)),
                ('Paciente_comuna_idcomuna', models.IntegerField()),
                ('Paciente_comuna_doctor_iddoctor', models.IntegerField()),
                ('Medico_idmedico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medico')),
                ('Paciente_idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('idTipoUsuario', models.IntegerField(primary_key=True, serialize=False)),
                ('tipousuario', models.CharField(max_length=45)),
                ('usuario_idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='respuestas_has_medico',
            fields=[
                ('informe_idinforme', models.IntegerField(primary_key=True, serialize=False)),
                ('Medico_idmedico', models.IntegerField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('idprovincia', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.region')),
            ],
        ),
        migrations.CreateModel(
            name='PreguntasInstrumento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('idtipoinstrumento', models.IntegerField()),
                ('descripcion', models.CharField(max_length=500)),
                ('TipoRespuesta_idTipoRespuesta', models.IntegerField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='PacienteHasFamiliarPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paciente_idPaciente', models.IntegerField()),
                ('Paciente_comuna_idcomuna', models.IntegerField()),
                ('Paciente_comuna_doctor_iddoctor', models.IntegerField()),
                ('FamiliarPaciente_idFamiliarPaciente', models.IntegerField()),
                ('primary_key', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('Paciente_idPaciente', 'Paciente_comuna_idcomuna', 'Paciente_comuna_doctor_iddoctor', 'FamiliarPaciente_idFamiliarPaciente')},
            },
        ),
        migrations.CreateModel(
            name='Paciente_has_Preguntas',
            fields=[
                ('Paciente_idPaciente', models.IntegerField(primary_key=True, serialize=False)),
                ('Paciente_comuna_idcomuna', models.IntegerField()),
                ('Paciente_comuna_doctor_iddoctor', models.IntegerField()),
                ('Preguntas_idPreguntas', models.IntegerField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente_has_Paciente_ProfesionalSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paciente_comuna_idcomuna', models.IntegerField()),
                ('Paciente_comuna_doctor_iddoctor', models.IntegerField()),
                ('Paciente_ProfesionalSalud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente_profesionalsalud')),
                ('Paciente_idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='MedicoHasEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico_idmedico', models.IntegerField()),
                ('especialidad_idespecialidad', models.IntegerField()),
                ('primary_key', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('medico_idmedico', 'especialidad_idespecialidad')},
            },
        ),
        migrations.CreateModel(
            name='Medico_has_Paciente_ProfesionalSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medico_idmedico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medico')),
                ('Paciente_ProfesionalSalud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente_profesionalsalud')),
            ],
        ),
        migrations.CreateModel(
            name='Medico_has_Paciente',
            fields=[
                ('Medico_idmedico', models.IntegerField(primary_key=True, serialize=False)),
                ('Paciente_idPaciente', models.IntegerField()),
                ('Paciente_comuna_idcomuna', models.IntegerField()),
                ('Paciente_comuna_doctor_iddoctor', models.IntegerField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Medico_has_Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.especialidad')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medico')),
            ],
        ),
        migrations.CreateModel(
            name='InstitucionHasMedicoHasEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institucion_idInstitucion', models.IntegerField()),
                ('Medico_has_especialidad_Medico_idmedico', models.IntegerField()),
                ('doctor_has_especialidad_especialidad_idespecialidad', models.IntegerField()),
                ('primary_key', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('Institucion_idInstitucion', 'Medico_has_especialidad_Medico_idmedico', 'doctor_has_especialidad_especialidad_idespecialidad')},
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('idInstitucion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='FamiliarPaciente',
            fields=[
                ('idFamiliarPaciente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('run', models.CharField(max_length=45)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.provincia'),
        ),
    ]
